[colors.bright]
black = "0x6f6b67"
blue = "0x278ad6"
cyan = "0x27dede"
green = "0x16c98d"
magenta = "0xd34590"
red = "0xfa5e5b"
white = "0xffffff"
yellow = "0xfeef6d"

[colors.cursor]
cursor = "0xb4b1b1"
text = "CellBackground"

[colors.normal]
black = "0x080200"
blue = "0x288ad6"
cyan = "0x28ddde"
green = "0x16c98d"
magenta = "0xd34590"
red = "0xfa5e5b"
white = "0xe7e7e7"
yellow = "0xffc83f"

[colors.primary]
background = "0x282828"
foreground = "0xeeeeee"

[font]
size = 16
normal = { family = "Hack Nerd Font Mono" }
bold = { family = "Hack Nerd Font Mono" }
italic = { family = "Hack Nerd Font Mono" }
glyph_offset = { x = 0, y = 2 }
offset = { x = 0, y = 3 }

[scrolling]
multiplier = 1

[keyboard]
bindings = [
  { key = "Equals", mods = "Control", action = "None" },
  { key = "Plus", mods = "Control", action = "None" },
  { key = "Minus", mods = "Control", action = "None" },
  { key = "Equals", mods = "Command", action = "None" },
  { key = "Plus", mods = "Command", action = "None" },
  { key = "Minus", mods = "Command", action = "None" },
  { key = "W", mods = "Command", action = "None" },
  { key = "W", mods = "Control|Shift", chars = "\u0000q" },
  { key = "Tab", mods = "Control|Shift", chars = "\u0000p" },
  { key = "Tab", mods = "Control", chars = "\u0000n" },
  { key = "Key1", mods = "Control", chars = "\u00001" },
  { key = "Key2", mods = "Control", chars = "\u00002" },
  { key = "Key3", mods = "Control", chars = "\u00003" },
  { key = "Key4", mods = "Control", chars = "\u00004" },
  { key = "Key5", mods = "Control", chars = "\u00005" },
  { key = "Key6", mods = "Control", chars = "\u00006" },
  { key = "Key7", mods = "Control", chars = "\u00007" },
  { key = "Key8", mods = "Control", chars = "\u00008" },
  { key = "Key9", mods = "Control", chars = "\u00009" },
]

[window]
decorations = "full"
startup_mode = "Maximized"
title = ""
